using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CapaEntidad
{
    class Consultas
    {
        //public string cashbox = "SELECT CAST(LCR_DENOMINATION_VALUE AS FLOAT) AS TYPE, LCR_STOCK AS CANT, ROUND((CAST(LCR_DENOMINATION_VALUE AS FLOAT) * LCR_STOCK),2) AS VALUE FROM LOG_CURRENT_LEVEL WHERE LCR_STOCK > 0 AND LCR_SHELF_CHANNEL_TYPE = 'input' ORDER BY LCR_SHELF_CHANNEL_TYPE, LCR_DENOMINATION_VALUE DESC";
        public string cashbox = "SELECT LCR_DENOMINATION_VALUE AS TYPE, SUM(LCR_STOCK)* LCR_DENOMINATION_VALUE AS VALUE, SUM(LCR_STOCK) AS CANT FROM LOG_CURRENT_LEVEL WHERE LCR_SHELF_CHANNEL_TYPE='INPUT' AND LCR_STOCK > 0 GROUP BY LCR_DENOMINATION_VALUE ORDER BY LCR_DENOMINATION_VALUE DESC";
        public string stock = "SELECT CAST(LCR_DENOMINATION_VALUE AS FLOAT) AS TYPE, SUM(LCR_STOCK) AS CANT,CAST(LCR_DENOMINATION_VALUE AS FLOAT) * SUM(LCR_STOCK) AS VALUE FROM LOG_CURRENT_LEVEL WHERE LCR_STOCK > 0 AND LCR_SHELF_CHANNEL_TYPE <> 'input' GROUP BY LCR_DENOMINATION_VALUE ORDER BY LCR_DENOMINATION_VALUE DESC";
        public string ticket = "SELECT LTI_FROM AS TYPE, SUM(LTI_AMOUNT) AS TOTAL FROM LOG_TICKET WHERE LTI_PAYOUT_DATE IS NOT NULL GROUP BY LTI_FROM ORDER BY LTI_FROM";
        public string tecnausa = "SELECT TTimeStamp,MachineNumber,Betrag, TEXT FROM LOG_Tecnausa WHERE 1=1 ORDER BY TTimeStamp";
    }
}
